title: Yixiao (Carl) Cao
description: I usually do quant research ğŸ’» ğŸ“ˆ and drink coffee  â˜•. I'm also into badminton ğŸ¸, guitar ğŸ¸, books & movies ğŸ“š, and some video games ğŸ®.
theme: jekyll-theme-minimal
