title: Yixiao (Carl) Cao
description: I mostly do quant research ğŸ’» ğŸ“ˆ and drink coffee  â˜•. I'm also into debating ğŸ¤”, badminton ğŸ¸, guitar ğŸ¸, books & movies ğŸ“š, and some video games ğŸ®.
theme: jekyll-theme-minimal
avatar: ./images/IMG_9609.JPG
